"""Constants used throughout the test suite."""

# Test data configuration
SAMPLE_DAYS_LOOKBACK = 30
SAMPLE_BASE_OPEN = 100.0
SAMPLE_BASE_HIGH = 101.0
SAMPLE_BASE_LOW = 99.0
SAMPLE_BASE_CLOSE = 100.5
SAMPLE_VALUE_INCREMENT = 0.5
SAMPLE_BASE_VOLUME = 1000000
SAMPLE_VOLUME_INCREMENT = 10000
SAMPLE_DATE_FREQUENCY = "D"

# Test tickers
TEST_TICKER_AAPL = "AAPL"
TEST_TICKER_AAPL_LOWER = "aapl"
TEST_TICKER_TEST = "TEST"

# Test dates
TEST_DATE_2020 = "2020-01-01"
TEST_PERIODS = 3

# Environment variables
SKIP_INTEGRATION_ENV_VAR = "SKIP_INTEGRATION_TESTS"

# Error messages
ERROR_PREFIX = "Error: "
MISSING_TICKER_ERROR = "Missing argument 'TICKER'"
